apiVersion: v1
kind: Service
metadata:
  name: {{ include "codex-lb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codex-lb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "codex-lb.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 2455
      targetPort: http
      protocol: TCP
